/**
 * gmMusic.js tests using golden file comparison
 *
 * These tests verify gmMusic parsing against known-good outputs.
 * Golden files are generated by: node tests/generate-golden-music.js
 *
 * Note: We don't test actual audio playback - just parsing and serialization.
 */

import { describe, test, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load dependencies (they populate globalThis as side effect)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmMusic.js');

// Extract from globalThis
const { D64 } = globalThis;
const { gmMusic } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
}

// Helper to parse song from disk
function loadSongFromDisk(disk, fileName) {
    const fileData = disk.readFile(fileName);
    if (!fileData) throw new Error(`File not found: ${fileName}`);
    return new gmMusic(fileData);
}

// Helper to compare two songs
function songsMatch(song1, song2) {
    // Compare case-insensitively (decodeString returns lowercase)
    if (song1.name.toLowerCase() !== song2.name.toLowerCase()) return false;
    if (song1.tempo !== song2.tempo) return false;
    if (song1.instruments.length !== song2.instruments.length) return false;
    for (let i = 0; i < song1.instruments.length; i++) {
        if (song1.instruments[i] !== song2.instruments[i]) return false;
    }

    // Compare channels
    if (song1.channels.length !== song2.channels.length) return false;
    for (let ch = 0; ch < song1.channels.length; ch++) {
        if (song1.channels[ch].length !== song2.channels[ch].length) return false;
        for (let n = 0; n < song1.channels[ch].length; n++) {
            const n1 = song1.channels[ch][n];
            const n2 = song2.channels[ch][n];
            if (n1.durationByte !== n2.durationByte) return false;
            if (n1.pitch !== n2.pitch) return false;
            if (n1.isRest !== n2.isRest) return false;
            if (n1.isTied !== n2.isTied) return false;
        }
    }

    return true;
}

// Fixture song (from the IP-clean test disk):
//   MINUTE/SNG  — Jonathan's transcription of the Minute Waltz
//                 (3 channels, flute on all)

describe('gmMusic - parsing from disk', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    describe('MINUTE/SNG - 3-channel transcription', () => {
        let song, expected;
        beforeAll(() => {
            song = loadSongFromDisk(disk, 'MINUTE/SNG');
            expected = loadGoldenJSON('music-MINUTE-SNG.json');
        });

        test('parses with correct name', () => {
            expect(song.name.toLowerCase()).toBe(expected.name.toLowerCase());
        });

        test('parses with correct tempo', () => {
            expect(song.tempo).toBe(expected.tempo);
        });

        test('parses with correct instruments', () => {
            expect(song.instruments).toEqual(expected.instruments);
        });

        test('has correct note counts per channel', () => {
            expect(song.channels[0].length).toBe(expected.channelNoteCounts[0]);
            expect(song.channels[1].length).toBe(expected.channelNoteCounts[1]);
            expect(song.channels[2].length).toBe(expected.channelNoteCounts[2]);
        });

        test('all three channels are populated', () => {
            // The whole point of multi-channel parsing — make sure the
            // parser splits notes across all three channels rather than
            // shoving everything into channel 0.
            for (let ch = 0; ch < 3; ch++) {
                expect(song.channels[ch].length).toBeGreaterThan(0);
            }
        });
    });
});

describe('gmMusic - serialization round-trip', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('MINUTE/SNG round-trips correctly', () => {
        const original = loadSongFromDisk(disk, 'MINUTE/SNG');
        const reloaded = new gmMusic(original.serialize());
        expect(songsMatch(original, reloaded)).toBe(true);
    });

    test('MINUTE/SNG serialized data can be parsed back identically', () => {
        const original = loadSongFromDisk(disk, 'MINUTE/SNG');
        const reparsed = new gmMusic(original.serialize());

        expect(reparsed.name.toLowerCase()).toBe(original.name.toLowerCase());
        expect(reparsed.tempo).toBe(original.tempo);
        expect(reparsed.instruments).toEqual(original.instruments);

        for (let ch = 0; ch < 3; ch++) {
            expect(reparsed.channels[ch].length).toBe(original.channels[ch].length);
            for (let n = 0; n < original.channels[ch].length; n++) {
                expect(reparsed.channels[ch][n].durationByte)
                    .toBe(original.channels[ch][n].durationByte);
                expect(reparsed.channels[ch][n].pitch)
                    .toBe(original.channels[ch][n].pitch);
            }
        }
    });
});

describe('gmMusic - note properties (generic invariants)', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('duration values are from the GM-supported set', () => {
        const song = loadSongFromDisk(disk, 'MINUTE/SNG');
        const validDurations = [0.125, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0];
        for (const channel of song.channels) {
            for (const note of channel) {
                expect(validDurations).toContain(note.duration);
            }
        }
    });

    test('pitch values are in valid range (0..127)', () => {
        const song = loadSongFromDisk(disk, 'MINUTE/SNG');
        for (const channel of song.channels) {
            for (const note of channel) {
                expect(note.pitch).toBeGreaterThanOrEqual(0);
                expect(note.pitch).toBeLessThanOrEqual(127);
            }
        }
    });
});

describe('gmMusic - createBlank', () => {
    test('creates blank song with defaults', () => {
        const song = gmMusic.createBlank();

        expect(song.name.trim()).toBe('NEW');
        expect(song.tempo).toBe(80);
        expect(song.instruments).toEqual([7, 12, 1]); // piano, violin, bass
        expect(song.channels).toEqual([[], [], []]);
    });

    test('creates blank song with custom options', () => {
        const song = gmMusic.createBlank({
            name: 'TEST',
            tempo: 100,
            instruments: [0, 1, 2]
        });

        expect(song.name.trim()).toBe('TEST');
        expect(song.tempo).toBe(100);
        expect(song.instruments).toEqual([0, 1, 2]);
    });

    test('blank song round-trips correctly', () => {
        const original = gmMusic.createBlank({ name: 'BLANK', tempo: 90 });
        const serialized = original.serialize();
        const reloaded = new gmMusic(serialized);

        expect(reloaded.name.toLowerCase()).toBe('blank');
        expect(reloaded.tempo).toBe(90);
        expect(reloaded.channels).toEqual([[], [], []]);
    });
});
