/**
 * gmParser.js tests using golden file comparison
 *
 * These tests verify gmParser parsing and round-trip serialization.
 * Golden files are generated by: node tests/generate-golden-programs.js
 *
 * Testing strategy:
 * - Capture mediaStore summary (type, name, quadIndex) - not indices
 * - Capture instruction text list (includes dereferenced comments, print strings, media names)
 * - Round-trip: parse → serialize → parse should produce identical summary/text
 */

import { describe, test, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load all dependencies (they populate globalThis as side effect)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmOpcodes.js');
await import('../js/gmSprite.js');
await import('../js/gmScene.js');
await import('../js/gmSound.js');
await import('../js/gmMusic.js');

// Suppress debug output
globalThis.debugLog = () => {};

// Load gmParser after globals are set
await import('../js/gmParser.js');

// Extract from globalThis
const { D64 } = globalThis;
const { decodeString, encodeString, c64ColorNames, encodeChar } = globalThis;
const { gmOpcodes, formatInstruction } = globalThis;
const { gmSprite, gmScene, gmSound, gmMusic } = globalThis;
const { parseProgramData, serializeProgram, buildAST, isMarkerEntry } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Current disk for loadFileByName
let currentDisk = null;
globalThis.loadFileByName = (fileName) => {
    if (!currentDisk) return null;
    return currentDisk.readFile(fileName);
};

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
}

// Helper to extract instruction list from parsed program
function getInstructionList(programData) {
    return programData.instructions.map(instr => {
        let line = '     ';
        if (instr.label > 0) {
            line = 'l' + instr.label.toString().padStart(3, '0') + ' ';
        }
        line += instr.instructionName;
        return line;
    });
}

// Helper to extract mediaStore summary
function getMediaStoreSummary(programData) {
    const summary = [];
    for (let i = 1; i < programData.mediaStore.length; i++) {
        const entry = programData.mediaStore[i];
        if (!entry) continue;

        summary.push({
            index: i,
            type: entry.type,
            name: entry.name,
            quadIndex: entry.quadIndex || 0
        });
    }
    return summary;
}

// Helper to compare two program representations
function programsMatch(prog1Summary, prog2Summary, prog1Instructions, prog2Instructions) {
    // Compare instruction lists
    if (prog1Instructions.length !== prog2Instructions.length) {
        console.log(`Instruction count mismatch: ${prog1Instructions.length} vs ${prog2Instructions.length}`);
        return false;
    }

    for (let i = 0; i < prog1Instructions.length; i++) {
        if (prog1Instructions[i] !== prog2Instructions[i]) {
            console.log(`Instruction ${i} mismatch:`);
            console.log(`  Original: ${prog1Instructions[i]}`);
            console.log(`  Reloaded: ${prog2Instructions[i]}`);
            return false;
        }
    }

    // Compare media store summaries (by type and name, not by index)
    // Sort both by type+name for comparison since indices may differ
    const sorted1 = [...prog1Summary].sort((a, b) =>
        (a.type + a.name + a.quadIndex).localeCompare(b.type + b.name + b.quadIndex));
    const sorted2 = [...prog2Summary].sort((a, b) =>
        (a.type + a.name + a.quadIndex).localeCompare(b.type + b.name + b.quadIndex));

    if (sorted1.length !== sorted2.length) {
        console.log(`MediaStore count mismatch: ${sorted1.length} vs ${sorted2.length}`);
        return false;
    }

    for (let i = 0; i < sorted1.length; i++) {
        const e1 = sorted1[i];
        const e2 = sorted2[i];
        if (e1.type !== e2.type || e1.name !== e2.name ||
            e1.quadIndex !== e2.quadIndex) {
            console.log(`MediaStore entry mismatch:`);
            console.log(`  Original: ${JSON.stringify(e1)}`);
            console.log(`  Reloaded: ${JSON.stringify(e2)}`);
            return false;
        }
    }

    return true;
}

describe('gmParser - parsing from disk', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
        currentDisk = disk;
    });

    // GMC64I exercises the heavy parser surface: multi-part sprites,
    // data tables, scene plotting opcodes, many comments, embedded music
    // and sounds.
    describe('GMC64I/PRG - intro demo (multi-part sprites, plotting, music)', () => {
        let programData;
        let expected;

        beforeAll(() => {
            const fileData = disk.readFile('GMC64I/PRG');
            programData = parseProgramData(fileData);
            expected = loadGoldenJSON('program-GMC64I-PRG.json');
        });

        test('parses correct number of instructions', () => {
            expect(programData.instructions.length).toBe(expected.instructionCount);
        });

        test('parses correct number of media entries', () => {
            const summary = getMediaStoreSummary(programData);
            expect(summary.length).toBe(expected.mediaStoreCount);
        });

        test('instruction list matches golden', () => {
            const instructionList = getInstructionList(programData);
            expect(instructionList).toEqual(expected.instructionList);
        });

        test('mediaStore summary matches golden', () => {
            const summary = getMediaStoreSummary(programData);
            expect(summary).toEqual(expected.mediaStoreSummary);
        });

        // SAUCER is the only 4-quad sprite + the only magnified sprite in
        // the test corpus. The 4-quad composition path (and the historical
        // snow-crash/5-byte-offset bug class around it) has zero coverage
        // without an explicit assertion here.
        test('SAUCER parses as a 4-quad sprite with magnification on', () => {
            const saucer = programData.mediaStore.find(e =>
                e?.sprite?.sprite?.[0]?.numSprites === 4);
            expect(saucer).toBeDefined();
            expect(saucer.name.toLowerCase().trim()).toBe('saucer');
            expect(saucer.sprite.sprite.length).toBe(4);
            const quad0 = saucer.sprite.sprite[0];
            expect(quad0.xDouble).toBe(true);
            expect(quad0.yDouble).toBe(true);
        });

        // Per-slot color path: GMC64I assigns BALOON/BFLY (and other
        // sprites) to multiple slots with different colors via opcode 0x2F
        // (sprite-color = literal). We assert here at parse-time rather
        // than after rendering — by the time the AST holds 0x2F at
        // different slots with different color values, the runtime path
        // is the only thing left between us and visible per-slot colors.
        // ALIENS PBULL/EBULL are the only hi-res sprites in the test corpus —
        // intentionally so, to give parsing + rendering of the non-multicolor
        // path coverage. tools/patch-aliens-bullets-hires.js converted them
        // and remapped pixels so the on-screen look is unchanged.
        test('ALIENS bullet sprites parse as hi-res', () => {
            const aliensPd = parseProgramData(disk.readFile('ALIENS/PRG'));
            const pbull = aliensPd.mediaStore.find(e =>
                e?.sprite && e.name.trim().toLowerCase() === 'pbull');
            const ebull = aliensPd.mediaStore.find(e =>
                e?.sprite && e.name.trim().toLowerCase() === 'ebull');
            expect(pbull).toBeDefined();
            expect(ebull).toBeDefined();
            expect(pbull.sprite.sprite[0].isMultiColor).toBe(false);
            expect(ebull.sprite.sprite[0].isMultiColor).toBe(false);
        });

        test('AST contains per-slot sprite-color assignments with distinct values', () => {
            function walk(nodes, out = []) {
                for (const n of nodes) {
                    out.push(n);
                    if (n.children) walk(n.children, out);
                }
                return out;
            }
            const colorsBySlot = new Map();
            for (const n of walk(programData.instructions)) {
                if (n.opcode !== 0x2F) continue;
                if (!colorsBySlot.has(n.arg1)) colorsBySlot.set(n.arg1, new Set());
                colorsBySlot.get(n.arg1).add(n.arg2);
            }
            expect(colorsBySlot.size).toBeGreaterThan(1);
            const firstColorPerSlot = [...colorsBySlot.values()].map(s => [...s][0]);
            expect(new Set(firstColorPerSlot).size).toBeGreaterThan(1);
        });
    });

    // ALIENS — original shooter. Smaller but interactively rich (data
    // tables for spawn positions, sprite swap-on-hit, scene bg mutation,
    // multi-part-aware enemy pairs).
    describe('ALIENS/PRG - shooter (data tables, sprite swaps, collision)', () => {
        let programData;
        let expected;

        beforeAll(() => {
            const fileData = disk.readFile('ALIENS/PRG');
            programData = parseProgramData(fileData);
            expected = loadGoldenJSON('program-ALIENS-PRG.json');
        });

        test('parses correct number of instructions', () => {
            expect(programData.instructions.length).toBe(expected.instructionCount);
        });

        test('instruction list matches golden', () => {
            const instructionList = getInstructionList(programData);
            expect(instructionList).toEqual(expected.instructionList);
        });

        test('mediaStore summary matches golden', () => {
            const summary = getMediaStoreSummary(programData);
            expect(summary).toEqual(expected.mediaStoreSummary);
        });
    });
});

describe('gmParser - round-trip serialization', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
        currentDisk = disk;
    });

    test('GMC64I/PRG round-trips correctly', () => {
        const fileData = disk.readFile('GMC64I/PRG');
        const original = parseProgramData(fileData);
        const originalInstructions = getInstructionList(original);
        const originalSummary = getMediaStoreSummary(original);

        // Serialize and re-parse
        const serialized = serializeProgram(original, fileData);
        const reloaded = parseProgramData(serialized);
        const reloadedInstructions = getInstructionList(reloaded);
        const reloadedSummary = getMediaStoreSummary(reloaded);

        expect(programsMatch(originalSummary, reloadedSummary,
            originalInstructions, reloadedInstructions)).toBe(true);
    });

    test('ALIENS/PRG round-trips correctly', () => {
        const fileData = disk.readFile('ALIENS/PRG');
        const original = parseProgramData(fileData);
        const originalInstructions = getInstructionList(original);
        const originalSummary = getMediaStoreSummary(original);

        const serialized = serializeProgram(original, fileData);
        const reloaded = parseProgramData(serialized);
        const reloadedInstructions = getInstructionList(reloaded);
        const reloadedSummary = getMediaStoreSummary(reloaded);

        expect(programsMatch(originalSummary, reloadedSummary,
            originalInstructions, reloadedInstructions)).toBe(true);
    });
});

describe('gmParser - multi-part sprite round-trip uses quadIndex for marker detection', () => {
    // Regression test for a class of bugs around marker-entry detection in
    // multi-part sprites. Markers are identified by isMarkerEntry() (which
    // wraps quadIndex > 0). The previous duplicate isMarker flag was removed
    // because it could drop out through serialization paths and silently
    // corrupt multi-part sprites — see commit history for the original bug.
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
        currentDisk = disk;
    });

    test('GMC64I (multi-part sprites) round-trips with marker entries intact', () => {
        // GMC64I and ALIENS both have multi-part sprites — pick GMC64I
        // because it has the more varied set (several multi-quad sprites
        // with different quad counts, exercising more of the marker path).
        const fileData = disk.readFile('GMC64I/PRG');
        const programData = parseProgramData(fileData);

        // Sanity: at least one marker entry
        const markersBefore = programData.mediaStore.filter(isMarkerEntry);
        expect(markersBefore.length).toBeGreaterThan(0);

        // Round-trip
        const serialized = serializeProgram(programData, fileData);
        const reloaded = parseProgramData(serialized);

        // Same marker count after the round-trip
        const markersAfter = reloaded.mediaStore.filter(isMarkerEntry);
        expect(markersAfter.length).toBe(markersBefore.length);

        // Full content match
        const origInstr = getInstructionList(programData);
        const origSum   = getMediaStoreSummary(programData);
        const reloadedInstr = getInstructionList(reloaded);
        const reloadedSum   = getMediaStoreSummary(reloaded);
        expect(programsMatch(origSum, reloadedSum, origInstr, reloadedInstr)).toBe(true);
    });
});

describe('gmParser - buildAST rebuilds dataTables from current instructions', () => {
    // Regression test for a bug where editing a "data values" (0x1D) instruction
    // in the editor would update programData.instructions but the runtime would
    // keep reading from the originally-parsed dataTables cache. buildAST now
    // rebuilds dataTables from the current instruction list so edits flow through.
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
        currentDisk = disk;
    });

    test('buildAST reflects edits made to a data-values instruction', () => {
        // GMC64I has data tables (animation/state lookups). ALIENS doesn't
        // use any — the picker-aim logic is variable-driven, not table-
        // driven — so GMC64I is the only available fixture with the right
        // shape (labelled 0x1D run).
        const fileData = disk.readFile('GMC64I/PRG');
        const programData = parseProgramData(fileData);

        // Find the first data-values instruction that starts a labeled table.
        const labelIdx = programData.instructions.findIndex(
            instr => instr.opcode === 0x1D && instr.label > 0
        );
        expect(labelIdx).toBeGreaterThan(-1);

        const startInstr = programData.instructions[labelIdx];
        const label = startInstr.label;
        const originalArg1 = startInstr.arg1;
        const originalArg2 = startInstr.arg2;

        // Sanity: the originally-parsed dataTables agrees with the instruction
        const ast0 = buildAST(programData);
        expect(ast0.dataTables[label][0]).toBe(originalArg1);
        expect(ast0.dataTables[label][1]).toBe(originalArg2);

        // Now simulate an editor edit: mutate the values on the instruction
        programData.instructions[labelIdx].arg1 = 99;
        programData.instructions[labelIdx].arg2 = 111;

        // buildAST should pick up the new values
        const ast1 = buildAST(programData);
        expect(ast1.dataTables[label][0]).toBe(99);
        expect(ast1.dataTables[label][1]).toBe(111);
        // ...but the next pair in the same table should be untouched
        expect(ast1.dataTables[label][2]).toBe(ast0.dataTables[label][2]);
        expect(ast1.dataTables[label][3]).toBe(ast0.dataTables[label][3]);
    });

    test('buildAST does not include data-values from before any label', () => {
        // Synthetic program: a 0x1D instruction with no preceding label should
        // be ignored (currentDataLabel === null path in the accumulator).
        const programData = {
            instructions: [
                { label: 0, opcode: 0x1D, arg1: 1, arg2: 2 },  // orphan, no label yet
                { label: 5, opcode: 0x1D, arg1: 3, arg2: 4 },  // starts label 5
                { label: 0, opcode: 0x1D, arg1: 5, arg2: 6 },  // continues label 5
            ],
            mediaStore: [null],
            dataTables: {}
        };

        const ast = buildAST(programData);
        expect(ast.dataTables[5]).toEqual([3, 4, 5, 6]);
        // The orphan values aren't in any table
        expect(Object.keys(ast.dataTables)).toEqual(['5']);
    });
});

describe('gmParser - media types', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
        currentDisk = disk;
    });

    test('GMC64I contains sprites, sounds, and a song', () => {
        const fileData = disk.readFile('GMC64I/PRG');
        const programData = parseProgramData(fileData);
        const summary = getMediaStoreSummary(programData);

        const types = new Set(summary.map(e => e.type));
        expect(types.has('sprite')).toBe(true);
        expect(types.has('sound')).toBe(true);
        expect(types.has('song')).toBe(true);
        // GMC64I doesn't reference a scene (everything in mediaStore is
        // drawn or plotted), so we don't assert scene presence here.
    });

    test('GMC64I contains multi-part sprites (markers)', () => {
        const fileData = disk.readFile('GMC64I/PRG');
        const programData = parseProgramData(fileData);
        const summary = getMediaStoreSummary(programData);

        const markers = summary.filter(isMarkerEntry);
        expect(markers.length).toBeGreaterThan(0);
    });

    test('all ALIENS media entries have valid names', () => {
        const fileData = disk.readFile('ALIENS/PRG');
        const programData = parseProgramData(fileData);
        const summary = getMediaStoreSummary(programData);

        for (const entry of summary) {
            expect(entry.name).toBeDefined();
            expect(typeof entry.name).toBe('string');
            expect(entry.name.length).toBeGreaterThan(0);
        }
    });

    test('ALIENS contains a scene reference (STARS)', () => {
        const fileData = disk.readFile('ALIENS/PRG');
        const programData = parseProgramData(fileData);
        const summary = getMediaStoreSummary(programData);

        const scenes = summary.filter(e => e.type === 'scene');
        expect(scenes.length).toBeGreaterThan(0);
    });
});
