/**
 * gmRuntime.js tests using state snapshot comparison
 *
 * These tests verify gmVM execution by running real programs and capturing state.
 * Golden files are generated by: node tests/generate-golden-runtime.js
 *
 * Testing strategy:
 * - Load a real PRG file from the test disk
 * - Run for N steps with specific input sequences
 * - Capture VM state (variables, sprites, scores, etc.)
 * - Compare to golden snapshot
 */

import { describe, test, expect, beforeAll, beforeEach } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load all dependencies (they populate globalThis)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmOpcodes.js');
await import('../js/gmSprite.js');
await import('../js/gmScene.js');

// Mock c64Screen constants (used by gmRuntime.render())
globalThis.c64Screen = {
    WIDTH: 320,
    HEIGHT: 200
};

await import('../js/gmSound.js');
await import('../js/gmMusic.js');

// Set up loadFileByName before loading gmParser (it needs this for scene loading)
let currentDisk = null;
globalThis.loadFileByName = (fileName) => {
    if (!currentDisk) return null;
    return currentDisk.readFile(fileName);
};

await import('../js/gmParser.js');

// gmRuntime no longer reads ambient globals for these — they're per-VM
// config now. We pass skipPauseInstructions:true at vm.loadProgram time
// below (tests want to race past `pause for X` opcodes).

// Input state - will be manipulated during tests
globalThis.inputState = {
    joystick1: { up: false, down: false, left: false, right: false },
    joystick2: { up: false, down: false, left: false, right: false },
    button1: false,
    button2: false
};

// Helper function used by gmRuntime
globalThis.decode16bit = (lo, hi) => lo + (hi << 8);

// Mock AudioParam for gain/frequency nodes
function createMockAudioParam(initialValue = 1) {
    return {
        value: initialValue,
        setValueAtTime: () => {},
        linearRampToValueAtTime: () => {},
        exponentialRampToValueAtTime: () => {},
        cancelScheduledValues: () => {},
        setTargetAtTime: () => {}
    };
}

// Mock AudioContext class for gmMusic.js which creates its own context
class MockAudioContext {
    constructor() {
        this.currentTime = 0;
        this.state = 'running';
        this.sampleRate = 44100;
        this.destination = {};
    }
    createOscillator() {
        return {
            connect: () => {},
            start: () => {},
            stop: () => {},
            frequency: createMockAudioParam(440),
            type: 'square',
            setPeriodicWave: () => {}
        };
    }
    createGain() {
        return {
            connect: () => {},
            gain: createMockAudioParam(1)
        };
    }
    createPeriodicWave() {
        return {};
    }
    createBuffer(channels, length, sampleRate) {
        return {
            getChannelData: () => new Float32Array(length)
        };
    }
    createBufferSource() {
        return {
            connect: () => {},
            start: () => {},
            stop: () => {},
            buffer: null
        };
    }
    close() {
        return Promise.resolve();
    }
}

// Set up window with AudioContext for gmMusic.js
globalThis.window = {
    AudioContext: MockAudioContext,
    webkitAudioContext: MockAudioContext
};

// Stub audio context (no actual audio in tests)
globalThis.audioContext = new MockAudioContext();
globalThis.masterGain = { connect: () => {}, gain: { value: 1 } };

// Real charset — gmCharset has its bitmap data baked in (no external file
// deps), so this works in the test environment. Previously we stubbed it
// out with `loaded: undefined`, which silently skipped every print/draw
// path in the runtime — the printed text was being computed but never
// painted into the scene, leaving frame goldens that didn't reflect what
// the program actually displays. Loading the real charset closes that gap.
await import('../js/gmCharset.js');
globalThis.charset = new globalThis.gmCharset();

// Mock screen for testing (supports rendering)
class MockScreen {
    constructor() {
        this.width = 320;
        this.height = 200;
        this.pixels = new Uint8Array(320 * 200 * 4);
        this.ctx = {
            fillRect: () => {},
            strokeRect: () => {},
            fillText: () => {},
            fillStyle: '',
            strokeStyle: '',
            lineWidth: 1,
            font: ''
        };
    }
    clear(r = 0, g = 0, b = 0) {
        for (let i = 0; i < this.pixels.length; i += 4) {
            this.pixels[i] = r;
            this.pixels[i + 1] = g;
            this.pixels[i + 2] = b;
            this.pixels[i + 3] = 255;
        }
    }
    present() {} // No-op in tests
    getContext() { return this.ctx; }
}

// Now load gmRuntime after globals are set
await import('../js/gmRuntime.js');

// Extract from globalThis
const { D64, parseProgramData, buildAST, gmVM } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Helper to reset input state
function resetInput() {
    globalThis.inputState = {
        joystick1: { up: false, down: false, left: false, right: false },
        joystick2: { up: false, down: false, left: false, right: false },
        button1: false,
        button2: false
    };
}

// Helper to set joystick direction
function setJoystick(joystickNum, direction) {
    const joy = joystickNum === 1 ? globalThis.inputState.joystick1 : globalThis.inputState.joystick2;
    joy.up = direction === 'up';
    joy.down = direction === 'down';
    joy.left = direction === 'left';
    joy.right = direction === 'right';
}

// Helper to set button state
function setButton(buttonNum, pressed) {
    if (buttonNum === 1) globalThis.inputState.button1 = pressed;
    else globalThis.inputState.button2 = pressed;
}

// Helper to capture VM state snapshot
function captureState(vm) {
    return {
        // Variables (a-z)
        variables: Array.from({ length: 26 }, (_, i) => ({
            name: String.fromCharCode(97 + i),
            value: vm.vars[i],
            defined: vm.varsDefined[i]
        })).filter(v => v.defined),

        // Sprites (8 slots)
        sprites: vm.sprites.map((slot, i) => ({
            slot: i + 1,
            visible: slot.visible,
            name: slot.spriteName,
            x: Math.round(slot.x * 100) / 100,
            y: Math.round(slot.y * 100) / 100,
            speed: slot.speed,
            direction: slot.direction,
            animSpeed: slot.animSpeed,
            currentFrame: slot.currentFrame
        })),

        // Scenes
        scenes: vm.scenes.map((scene, i) => ({
            slot: i + 1,
            loaded: !!scene,
            name: scene?.name || null
        })),
        activeScene: vm.activeScene,

        // Scores
        scores: [...vm.score],

        // Execution state
        running: vm.running,
        paused: vm.paused,
        pc: vm.pc
    };
}

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    try {
        return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
    } catch (e) {
        return null; // Golden doesn't exist yet
    }
}

// Helper to load and set up VM with a program
function loadProgram(disk, programName) {
    // Set currentDisk for loadFileByName (used by gmParser for scene loading)
    currentDisk = disk;

    const fileData = disk.readFile(programName);
    if (!fileData) throw new Error(`Program not found: ${programName}`);

    const programData = parseProgramData(fileData);
    const ast = buildAST(programData);

    const screen = new MockScreen();
    const vm = new gmVM(screen, { skipPauseInstructions: true });
    vm.loadProgram(ast, fileData);
    vm.running = true;

    return { vm, fileData, programData };
}

// Helper to run VM for N steps
// Batches steps like the browser does: 50 steps per virtual frame, then
// updateSpritePositions + advanceSpriteAnimations (toggle alternating each
// virtual frame to match the real ~30fps animation cadence).
const STEPS_PER_FRAME = 50;
function runSteps(vm, steps) {
    let remaining = steps;
    let animToggle = false;
    while (remaining > 0 && vm.running) {
        const batch = Math.min(remaining, STEPS_PER_FRAME);
        for (let i = 0; i < batch && vm.running; i++) {
            vm.step();
        }
        vm.updateSpritePositions();
        animToggle = !animToggle;
        vm.advanceSpriteAnimations(animToggle);
        remaining -= batch;
    }
}

// Test fixtures: tests/disks/gmc64-test.d64 holds GMC64I (intro demo)
// and ALIENS (shooter). Together they cover the full runtime surface —
// multi-quad sprites, per-slot color, scene plotting, character
// printing, music, subroutines, data tables, sprite/sprite collision,
// joystick + button input.

describe('gmRuntime - GMC64I (intro demo) execution', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    beforeEach(() => {
        resetInput();
    });

    test('initial state after loading', () => {
        const { vm } = loadProgram(disk, 'GMC64I/PRG');
        const state = captureState(vm);

        expect(state.running).toBe(true);
        expect(state.pc).toBe(0);
        expect(state.variables.length).toBe(0);
        expect(state.sprites.every(s => !s.visible)).toBe(true);
    });

    test('state after 100 steps (initialization)', () => {
        const { vm } = loadProgram(disk, 'GMC64I/PRG');
        runSteps(vm, 100);
        const state = captureState(vm);

        const golden = loadGoldenJSON('runtime-GMC64I-100steps.json');
        if (golden) {
            expect(state.variables).toEqual(golden.variables);
            expect(state.sprites).toEqual(golden.sprites);
            expect(state.scores).toEqual(golden.scores);
        } else {
            expect(state.running).toBe(true);
        }
    });

    // The intro plots characters, dots, and uses subroutines + per-slot
    // sprite colors throughout. None of that visibly takes effect until
    // the demo has run for thousands of steps — early frames just show
    // setup. This golden + the frame golden below specifically exercise
    // those long-running paths.
    test('state after 5000 steps (long run, plotting + animation active)', () => {
        const { vm } = loadProgram(disk, 'GMC64I/PRG');
        runSteps(vm, 5000);
        const state = captureState(vm);

        const golden = loadGoldenJSON('runtime-GMC64I-5000steps.json');
        if (golden) {
            expect(state.variables).toEqual(golden.variables);
            expect(state.sprites).toEqual(golden.sprites);
            expect(state.scores).toEqual(golden.scores);
        } else {
            expect(state.running).toBe(true);
        }
    });

    test('rendered frame after 5000 steps matches golden (verifies plotting visible)', () => {
        const { vm } = loadProgram(disk, 'GMC64I/PRG');
        runSteps(vm, 5000);
        vm.renderPixels();

        const golden = loadGoldenJSON('runtime-GMC64I-5000-frame.json');
        if (golden) {
            const pixels = vm.screen.pixels;
            const goldenPixels = golden.pixelSamples;
            const sampleIndices = golden.sampleIndices;
            for (let i = 0; i < sampleIndices.length; i++) {
                const idx = sampleIndices[i];
                if (pixels[idx] !== goldenPixels[i]) {
                    const pixelNum = Math.floor(i / 4);
                    const x = (pixelNum % 40) * 8;
                    const y = Math.floor(pixelNum / 40) * 8;
                    throw new Error(`Pixel mismatch at (${x},${y}): got RGBA(${pixels[idx]},${pixels[idx+1]},${pixels[idx+2]},${pixels[idx+3]}) expected RGBA(${goldenPixels[i]},${goldenPixels[i+1]},${goldenPixels[i+2]},${goldenPixels[i+3]})`);
                }
            }
        } else {
            expect(vm.screen.pixels.length).toBe(320 * 200 * 4);
        }
    });
});

describe('gmRuntime - ALIENS execution', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    beforeEach(() => {
        resetInput();
    });

    test('initial state after loading', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        const state = captureState(vm);

        expect(state.running).toBe(true);
        expect(state.pc).toBe(0);
    });

    test('state after 100 steps', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        const state = captureState(vm);

        const golden = loadGoldenJSON('runtime-ALIENS-100steps.json');
        if (golden) {
            expect(state.variables).toEqual(golden.variables);
            expect(state.sprites).toEqual(golden.sprites);
            expect(state.scores).toEqual(golden.scores);
        } else {
            expect(state.running).toBe(true);
        }
    });

    test('joystick right moves the ship', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);  // setup completes
        const xBefore = vm.sprites[0].x;
        setJoystick(1, 'right');
        runSteps(vm, 100);
        expect(vm.sprites[0].x).toBeGreaterThan(xBefore);
    });

    test('button fires a bullet (f var goes 0 → 1)', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        // ALIENS' VAR_F (GM index 6 → array index 5) tracks player-bullet
        // active. 0 = ready, 1 = in flight.
        expect(vm.vars[5]).toBe(0);
        setButton(1, true);
        runSteps(vm, 50);
        expect(vm.vars[5]).toBe(1);
    });

    // Shared frame-comparison helper. Each scenario sets up input then
    // checks pixel samples against its golden — same logic as the per-test
    // version above, factored so the input-driven scenarios stay readable.
    function assertFrameMatchesGolden(vm, goldenName) {
        vm.renderPixels();
        const golden = loadGoldenJSON(goldenName);
        if (!golden) {
            expect(vm.screen.pixels.length).toBe(320 * 200 * 4);
            return;
        }
        const pixels = vm.screen.pixels;
        const goldenPixels = golden.pixelSamples;
        const sampleIndices = golden.sampleIndices;
        for (let i = 0; i < sampleIndices.length; i++) {
            const idx = sampleIndices[i];
            if (pixels[idx] !== goldenPixels[i]) {
                const pixelNum = Math.floor(i / 4);
                const x = (pixelNum % 40) * 8;
                const y = Math.floor(pixelNum / 40) * 8;
                throw new Error(`${goldenName} pixel mismatch at (${x},${y}): got RGBA(${pixels[idx]},${pixels[idx+1]},${pixels[idx+2]},${pixels[idx+3]}) expected RGBA(${goldenPixels[i]},${goldenPixels[i+1]},${goldenPixels[i+2]},${goldenPixels[i+3]})`);
            }
        }
    }

    test('rendered frame after 100 steps matches golden', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        assertFrameMatchesGolden(vm, 'runtime-ALIENS-100-frame.json');
    });

    // One combined-input frame covers movement, firing, and collision in
    // a single image. Inputs are staggered so the ship starts drifting
    // right BEFORE the first bullet is fired:
    //   steps   1–100 : no input
    //   step      100 : joystick right
    //   step      110 : button (in addition)
    //   thereafter    : run until score increments, then snapshot.
    // End-state shows ship shifted right, an alien removed, score=10.
    test('rendered frame after combined right+fire until first collision matches golden', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        setJoystick(1, 'right');
        runSteps(vm, 10);
        setButton(1, true);
        let steps = 0;
        while (steps < 4000 && vm.score[0] === 0) {
            runSteps(vm, 100);
            steps += 100;
        }
        expect(vm.score[0]).toBeGreaterThan(0);
        assertFrameMatchesGolden(vm, 'runtime-ALIENS-combined-frame.json');
    });
});

describe('gmRuntime - variable operations', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('ALIENS sets variables during initialization', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        const state = captureState(vm);
        expect(state.variables.length).toBeGreaterThan(0);
    });
});

describe('gmRuntime - collision detection', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('sprites have correct bounding boxes', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);

        // Check that visible sprites have valid hitboxes
        for (let i = 0; i < 8; i++) {
            const slot = vm.sprites[i];
            if (slot.visible && slot.spriteInstance) {
                const hitboxes = vm.getAllHitboxes(i);
                expect(hitboxes.length).toBeGreaterThan(0);

                for (const hitbox of hitboxes) {
                    expect(hitbox.width).toBeGreaterThan(0);
                    expect(hitbox.height).toBeGreaterThan(0);
                }
            }
        }
    });

    // End-to-end collision test: hold the fire button long enough for a
    // bullet to travel up the screen, overlap an alien, and trip the
    // hit-handler that increments score1. Probe showed score becomes
    // non-zero by ~step 2000; we cap at 4000 for headroom against timing
    // tweaks. If this regresses, sprite-sprite collision is broken.
    test('button held → bullet hits alien → score1 increases', () => {
        const { vm } = loadProgram(disk, 'ALIENS/PRG');
        runSteps(vm, 100);
        expect(vm.score[0]).toBe(0);

        setButton(1, true);
        let stepsUsed = 0;
        const MAX_STEPS = 4000;
        while (stepsUsed < MAX_STEPS && vm.score[0] === 0) {
            runSteps(vm, 100);
            stepsUsed += 100;
        }
        expect(vm.score[0]).toBeGreaterThan(0);
    });
});
