/**
 * gmScene.js tests using golden file comparison
 *
 * These tests verify gmScene parsing against known-good outputs.
 * Golden files are generated by: node tests/generate-golden-scenes.js
 */

import { describe, test, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load dependencies (they populate globalThis as side effect)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmScene.js');

// Extract from globalThis
const { D64 } = globalThis;
const { gmScene } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
}

// Helper to parse scene from disk
function loadSceneFromDisk(disk, fileName) {
    const fileData = disk.readFile(fileName);
    if (!fileData) throw new Error(`File not found: ${fileName}`);
    return new gmScene(fileData);
}

// Helper to compare two scenes
function scenesMatch(scene1, scene2) {
    // Names are compared case-insensitively (C64 displays uppercase but decodes to lowercase)
    if (scene1.name.toLowerCase() !== scene2.name.toLowerCase()) return false;
    if (scene1._bgColor !== scene2._bgColor) return false;
    if (scene1._color1 !== scene2._color1) return false;
    if (scene1._color2 !== scene2._color2) return false;
    if (scene1._color3 !== scene2._color3) return false;

    // Compare pixel buffers
    if (scene1.pixelBuffer.length !== scene2.pixelBuffer.length) return false;
    for (let i = 0; i < scene1.pixelBuffer.length; i++) {
        if (scene1.pixelBuffer[i] !== scene2.pixelBuffer[i]) return false;
    }

    return true;
}

// Fixture scenes (IP-clean test disk):
//   MEADOW/PIC  — Jonathan's sunlit meadow (RLE compressed)
//   STARS /PIC  — starfield (mostly empty bg, compresses very well; note
//                 trailing space in the filename — significant)

describe('gmScene - parsing from disk', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    describe('MEADOW/PIC', () => {
        let scene, expected;
        beforeAll(() => {
            scene = loadSceneFromDisk(disk, 'MEADOW/PIC');
            expected = loadGoldenJSON('scene-MEADOW-PIC.json');
        });

        test('parses with correct name', () => {
            expect(scene.name).toBe(expected.name);
        });

        test('parses with correct colors', () => {
            expect(scene._bgColor).toBe(expected.bgColor);
            expect(scene._color1).toBe(expected.color1);
            expect(scene._color2).toBe(expected.color2);
            expect(scene._color3).toBe(expected.color3);
        });

        test('has correct pixel buffer size', () => {
            expect(scene.pixelBuffer.length).toBe(160 * 200);
        });

        test('pixel buffer matches golden', () => {
            const expectedBuffer = Buffer.from(expected.pixelBuffer, 'base64');
            expect(Buffer.from(scene.pixelBuffer)).toEqual(expectedBuffer);
        });

        test('pixel checksum matches', () => {
            const checksum = Array.from(scene.pixelBuffer).reduce((a, b) => a + b, 0);
            expect(checksum).toBe(expected.pixelChecksum);
        });
    });

    describe('STARS /PIC', () => {
        let scene, expected;
        beforeAll(() => {
            scene = loadSceneFromDisk(disk, 'STARS /PIC');
            expected = loadGoldenJSON('scene-STARS_-PIC.json');
        });

        test('parses with correct name', () => {
            expect(scene.name).toBe(expected.name);
        });

        test('parses with correct colors', () => {
            expect(scene._bgColor).toBe(expected.bgColor);
            expect(scene._color1).toBe(expected.color1);
        });

        test('decompresses RLE correctly', () => {
            expect(expected.isRLE).toBe(true);
            expect(scene.pixelBuffer.length).toBe(160 * 200);
        });

        test('pixel buffer matches golden', () => {
            const expectedBuffer = Buffer.from(expected.pixelBuffer, 'base64');
            expect(Buffer.from(scene.pixelBuffer)).toEqual(expectedBuffer);
        });
    });
});

describe('gmScene - serialization round-trip', () => {
    let disk;
    const FIXTURES = ['MEADOW/PIC', 'STARS /PIC'];

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test.each(FIXTURES)('%s round-trips correctly', (name) => {
        const original = loadSceneFromDisk(disk, name);
        const reloaded = new gmScene(original.save());
        expect(scenesMatch(original, reloaded)).toBe(true);
    });

    test('saved data uses RLE when smaller', () => {
        // save() chooses RLE or uncompressed based on which is smaller
        const uncompressedSize = 6 + 8000 + 10; // 8016 bytes
        for (const name of FIXTURES) {
            const scene = loadSceneFromDisk(disk, name);
            const saved = scene.save();
            expect(saved.length).toBeLessThanOrEqual(uncompressedSize);
            const isRLE = saved[5] === 0xFF;
            if (saved.length < uncompressedSize) expect(isRLE).toBe(true);
            else expect(isRLE).toBe(false);
        }
    });

    test('saved data can be parsed back identically', () => {
        for (const name of FIXTURES) {
            const original = loadSceneFromDisk(disk, name);
            const reparsed = new gmScene(original.save());

            expect(reparsed.name.toLowerCase()).toBe(original.name.toLowerCase());
            expect(reparsed._bgColor).toBe(original._bgColor);
            expect(reparsed._color1).toBe(original._color1);
            expect(reparsed._color2).toBe(original._color2);
            expect(reparsed._color3).toBe(original._color3);
            expect(Buffer.from(reparsed.pixelBuffer)).toEqual(Buffer.from(original.pixelBuffer));
        }
    });

    test('all fixture scenes expand to the full 32000-pixel buffer', () => {
        for (const name of FIXTURES) {
            const scene = loadSceneFromDisk(disk, name);
            expect(scene.pixelBuffer.length).toBe(32000);
        }
    });
});

describe('gmScene - RLE compression', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('STARS /PIC compresses significantly (mostly empty background)', () => {
        const scene = loadSceneFromDisk(disk, 'STARS /PIC');
        const saved = scene.save();
        expect(saved[5]).toBe(0xFF); // RLE flag set
        expect(saved.length).toBeLessThan(1000);
    });

    test('blank scene compresses to minimum size', () => {
        const scene = gmScene.createBlank();
        const saved = scene.save();
        expect(saved[5]).toBe(0xFF); // RLE flag set
        // 8000 bytes of zeros compresses to ~80 RLE pairs + footer
        expect(saved.length).toBeLessThan(200);
    });

    test('RLE compression is reversible', () => {
        for (const name of ['MEADOW/PIC', 'STARS /PIC']) {
            const original = loadSceneFromDisk(disk, name);
            const reloaded = new gmScene(original.save());
            expect(Buffer.from(reloaded.pixelBuffer)).toEqual(Buffer.from(original.pixelBuffer));
        }
    });
});

describe('gmScene - blank scene creation', () => {
    test('createBlank creates scene with specified colors', () => {
        const scene = gmScene.createBlank(6, 1, 9, 0);

        expect(scene._bgColor).toBe(6);
        expect(scene._color1).toBe(1);
        expect(scene._color2).toBe(9);
        expect(scene._color3).toBe(0);
        expect(scene.name).toBe('SCENE');
    });

    test('blank scene has all pixels set to background (0)', () => {
        const scene = gmScene.createBlank();
        const allZero = scene.pixelBuffer.every(p => p === 0);
        expect(allZero).toBe(true);
    });

    test('blank scene round-trips correctly', () => {
        const original = gmScene.createBlank(3, 7, 11, 15);
        original.name = 'TEST';
        const saved = original.save();
        const reloaded = new gmScene(saved);

        expect(scenesMatch(original, reloaded)).toBe(true);
    });
});
