/**
 * gmSound.js tests using golden file comparison
 *
 * These tests verify gmSound parsing against known-good outputs.
 * Golden files are generated by: node tests/generate-golden-sounds.js
 *
 * Note: We don't test actual audio playback - just parsing and serialization.
 */

import { describe, test, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load dependencies (they populate globalThis as side effect)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmSound.js');

// Extract from globalThis
const { D64 } = globalThis;
const { gmSound } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
}

// Helper to parse sound from disk
function loadSoundFromDisk(disk, fileName) {
    const fileData = disk.readFile(fileName);
    if (!fileData) throw new Error(`File not found: ${fileName}`);
    return new gmSound(fileData);
}

// Helper to compare two sounds
function soundsMatch(sound1, sound2) {
    // Compare case-insensitively (decodeString returns lowercase)
    if (sound1.name.toLowerCase() !== sound2.name.toLowerCase()) return false;
    if (sound1.repeatCount !== sound2.repeatCount) return false;
    if (sound1.repeatDelay !== sound2.repeatDelay) return false;
    if (sound1.speed !== sound2.speed) return false;
    if (sound1.eqOn !== sound2.eqOn) return false;
    if (sound1.volume !== sound2.volume) return false;

    // Compare frames
    if (sound1.frames.length !== sound2.frames.length) return false;
    for (let i = 0; i < sound1.frames.length; i++) {
        const f1 = sound1.frames[i];
        const f2 = sound2.frames[i];

        if (f1.wave !== f2.wave) return false;
        if (f1.att !== f2.att) return false;
        if (f1.dec !== f2.dec) return false;
        if (f1.sus !== f2.sus) return false;
        if (f1.rel !== f2.rel) return false;
        if (f1.freqHi !== f2.freqHi) return false;
        if (f1.freqLo !== f2.freqLo) return false;
        if (f1.spd !== f2.spd) return false;
        if (f1.pulseHi !== f2.pulseHi) return false;
        if (f1.pulseLo !== f2.pulseLo) return false;
        if (f1.dur !== f2.dur) return false;
        if (f1.eqLowPass !== f2.eqLowPass) return false;
        if (f1.eqBandPass !== f2.eqBandPass) return false;
        if (f1.eqHighPass !== f2.eqHighPass) return false;
        if (f1.tie !== f2.tie) return false;
    }

    return true;
}

// Fixture sounds (from the IP-clean test disk):
//   ENGINE/SND  — 2-frame looped engine effect (repeat=100)
//   KCHEER/SND  — 2-frame one-shot cheer (repeat=0)

describe('gmSound - parsing from disk', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    describe('ENGINE/SND - looped sound (repeat=100)', () => {
        let sound, expected;
        beforeAll(() => {
            sound = loadSoundFromDisk(disk, 'ENGINE/SND');
            expected = loadGoldenJSON('sound-ENGINE-SND.json');
        });

        test('parses with correct name', () => {
            expect(sound.name.toLowerCase()).toBe(expected.name.toLowerCase());
        });

        test('parses with correct header properties', () => {
            expect(sound.repeatCount).toBe(expected.repeatCount);
            expect(sound.repeatDelay).toBe(expected.repeatDelay);
            expect(sound.speed).toBe(expected.speed);
            expect(sound.eqOn).toBe(expected.eqOn);
            expect(sound.volume).toBe(expected.volume);
        });

        test('has matching number of frames', () => {
            expect(sound.frames.length).toBe(expected.frames.length);
        });

        test('all frames match golden', () => {
            for (let i = 0; i < sound.frames.length; i++) {
                // The golden adds a synthetic `index` field per frame for
                // readability — the runtime doesn't, so strip it before
                // comparing.
                const { index, ...exp } = expected.frames[i];
                expect(sound.frames[i]).toEqual(exp);
            }
        });

        test('repeats (repeatCount > 0)', () => {
            expect(sound.repeatCount).toBeGreaterThan(0);
        });
    });

    describe('KCHEER/SND - one-shot sound (repeat=0)', () => {
        let sound, expected;
        beforeAll(() => {
            sound = loadSoundFromDisk(disk, 'KCHEER/SND');
            expected = loadGoldenJSON('sound-KCHEER-SND.json');
        });

        test('parses with correct name', () => {
            expect(sound.name.toLowerCase()).toBe(expected.name.toLowerCase());
        });

        test('does not repeat (repeatCount = 0)', () => {
            expect(sound.repeatCount).toBe(0);
        });

        test('all frames match golden', () => {
            for (let i = 0; i < sound.frames.length; i++) {
                // The golden adds a synthetic `index` field per frame for
                // readability — the runtime doesn't, so strip it before
                // comparing.
                const { index, ...exp } = expected.frames[i];
                expect(sound.frames[i]).toEqual(exp);
            }
        });
    });
});

describe('gmSound - serialization round-trip', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    const FIXTURES = ['ENGINE/SND', 'KCHEER/SND'];

    test.each(FIXTURES)('%s round-trips correctly', (name) => {
        const original = loadSoundFromDisk(disk, name);
        const reloaded = new gmSound(original.serialize());
        expect(soundsMatch(original, reloaded)).toBe(true);
    });

    test('serialized size matches expected format', () => {
        // Size = 18 (header) + 16 * frames + 1 (trailing zero)
        for (const name of FIXTURES) {
            const sound = loadSoundFromDisk(disk, name);
            const expectedSize = 18 + (16 * sound.frames.length) + 1;
            expect(sound.serialize().length).toBe(expectedSize);
        }
    });

    test('serialized data can be parsed back identically', () => {
        for (const name of FIXTURES) {
            const original = loadSoundFromDisk(disk, name);
            const reparsed = new gmSound(original.serialize());

            expect(reparsed.name.toLowerCase()).toBe(original.name.toLowerCase());
            expect(reparsed.repeatCount).toBe(original.repeatCount);
            expect(reparsed.speed).toBe(original.speed);
            expect(reparsed.frames.length).toBe(original.frames.length);

            for (let i = 0; i < original.frames.length; i++) {
                expect(reparsed.frames[i]).toEqual(original.frames[i]);
            }
        }
    });
});

describe('gmSound - frame properties (generic invariants)', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('ADSR values stay in valid range across all fixture sounds', () => {
        for (const name of ['ENGINE/SND', 'KCHEER/SND']) {
            const sound = loadSoundFromDisk(disk, name);
            for (const frame of sound.frames) {
                expect(frame.att).toBeGreaterThanOrEqual(0);
                expect(frame.att).toBeLessThanOrEqual(15);
                expect(frame.dec).toBeGreaterThanOrEqual(0);
                expect(frame.dec).toBeLessThanOrEqual(15);
                expect(frame.sus).toBeGreaterThanOrEqual(0);
                expect(frame.sus).toBeLessThanOrEqual(15);
                expect(frame.rel).toBeGreaterThanOrEqual(0);
                expect(frame.rel).toBeLessThanOrEqual(15);
            }
        }
    });
});
