/**
 * gmSprite.js tests using golden file comparison
 *
 * These tests verify gmSprite parsing against known-good outputs.
 * Golden files are generated by: node tests/generate-golden-sprites.js
 */

import { describe, test, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load dependencies (they populate globalThis as side effect)
await import('../js/c64lib.js');
await import('../js/d64lib.js');
await import('../js/gmSprite.js');

// Extract from globalThis
const { D64 } = globalThis;
const { gmSprite } = globalThis;

const GOLDEN_DIR = join(__dirname, 'golden');
const DISKS_DIR = join(__dirname, 'disks');

// Helper to load golden JSON
function loadGoldenJSON(filename) {
    return JSON.parse(readFileSync(join(GOLDEN_DIR, filename), 'utf-8'));
}

// Helper to parse sprite from disk
function loadSpriteFromDisk(disk, fileName) {
    const fileData = disk.readFile(fileName);
    if (!fileData) throw new Error(`File not found: ${fileName}`);
    return new gmSprite(fileData);
}

// Helper to serialize sprite for comparison (matches generator format)
function serializeSprite(sprite) {
    return {
        sizeInBytes: sprite.sizeInBytes,
        _bgColor: sprite._bgColor,
        _gmColor1: sprite._gmColor1,
        _gmColor2: sprite._gmColor2,
        _gmColor3: sprite._gmColor3,
        quads: sprite.sprite.map((quad, index) => ({
            quadIndex: index,
            spriteName: quad.spriteName,
            isMultiColor: quad.isMultiColor,
            numFrames: quad.numFrames,
            totalFrames: quad.totalFrames,
            numSprites: quad.numSprites,
            xDouble: quad.xDouble,
            yDouble: quad.yDouble,
            xPosition: quad.xPosition,
            yPosition: quad.yPosition,
            spriteNum: quad.spriteNum,
            _bgColor: quad._bgColor,
            _gmColor1: quad._gmColor1,
            _gmColor2: quad._gmColor2,
            _gmColor3: quad._gmColor3,
            imageData: quad.imageData.map(frame =>
                Buffer.from(frame).toString('base64')
            )
        }))
    };
}

// Helper to compare two sprites (ignoring rendered frames)
function spritesMatch(sprite1, sprite2) {
    // Compare top-level colors
    if (sprite1._bgColor !== sprite2._bgColor) return false;
    if (sprite1._gmColor1 !== sprite2._gmColor1) return false;
    if (sprite1._gmColor2 !== sprite2._gmColor2) return false;
    if (sprite1._gmColor3 !== sprite2._gmColor3) return false;

    // Compare quad count
    if (sprite1.sprite.length !== sprite2.sprite.length) return false;

    // Compare each quad
    for (let q = 0; q < sprite1.sprite.length; q++) {
        const q1 = sprite1.sprite[q];
        const q2 = sprite2.sprite[q];

        if (q1.spriteName !== q2.spriteName) return false;
        if (q1.isMultiColor !== q2.isMultiColor) return false;
        if (q1.numFrames !== q2.numFrames) return false;
        if (q1.totalFrames !== q2.totalFrames) return false;
        if (q1.numSprites !== q2.numSprites) return false;
        if (q1.xDouble !== q2.xDouble) return false;
        if (q1.yDouble !== q2.yDouble) return false;
        if (q1.xPosition !== q2.xPosition) return false;
        if (q1.yPosition !== q2.yPosition) return false;
        if (q1._bgColor !== q2._bgColor) return false;
        if (q1._gmColor1 !== q2._gmColor1) return false;
        if (q1._gmColor2 !== q2._gmColor2) return false;
        if (q1._gmColor3 !== q2._gmColor3) return false;

        // Compare frame data
        if (q1.imageData.length !== q2.imageData.length) return false;
        for (let f = 0; f < q1.imageData.length; f++) {
            const f1 = q1.imageData[f];
            const f2 = q2.imageData[f];
            if (f1.length !== f2.length) return false;
            for (let i = 0; i < f1.length; i++) {
                if (f1[i] !== f2[i]) return false;
            }
        }
    }

    return true;
}

// Fixture sprites live on tests/disks/gmc64-test.d64. The two standalone
// sprites here cover single-quad and multi-quad parsing paths. Hi-res
// and xDouble/yDouble coverage is provided by sprites embedded in
// GMC64I/PRG (SAUCER for 4-quad + magnification) and ALIENS/PRG
// (PBULL/EBULL for hi-res) — see gmParser.test.js.
//
//   PLAYER/SPR  — single-quad, multicolor, 8 frames
//   ALIENS/SPR  — 2-quad, multicolor, 6 frames per quad

describe('gmSprite - parsing from disk', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    describe('PLAYER/SPR - single-quad multicolor', () => {
        let sprite;
        let expected;

        beforeAll(() => {
            sprite = loadSpriteFromDisk(disk, 'PLAYER/SPR');
            expected = loadGoldenJSON('sprite-PLAYER-SPR.json');
        });

        test('parses with correct top-level properties', () => {
            expect(sprite.sizeInBytes).toBe(expected.sizeInBytes);
            expect(sprite._bgColor).toBe(expected._bgColor);
            expect(sprite._gmColor1).toBe(expected._gmColor1);
            expect(sprite._gmColor2).toBe(expected._gmColor2);
            expect(sprite._gmColor3).toBe(expected._gmColor3);
        });

        test('has one quad (single sprite)', () => {
            expect(sprite.sprite.length).toBe(1);
            expect(sprite.sprite[0].numSprites).toBe(1);
        });

        test('is multicolor mode', () => {
            expect(sprite.sprite[0].isMultiColor).toBe(true);
        });

        test('parses quad 0 with correct properties', () => {
            const actual = sprite.sprite[0];
            const exp = expected.quads[0];
            expect(actual.spriteName).toBe(exp.spriteName);
            expect(actual.isMultiColor).toBe(exp.isMultiColor);
            expect(actual.numFrames).toBe(exp.numFrames);
            expect(actual.totalFrames).toBe(exp.totalFrames);
            expect(actual.numSprites).toBe(exp.numSprites);
            expect(actual.xDouble).toBe(exp.xDouble);
            expect(actual.yDouble).toBe(exp.yDouble);
        });

        test('parses frame data correctly', () => {
            const actual = serializeSprite(sprite);
            expect(actual.quads[0].imageData).toEqual(expected.quads[0].imageData);
        });
    });

    describe('ALIENS/SPR - 2-quad multicolor', () => {
        let sprite;
        let expected;

        beforeAll(() => {
            sprite = loadSpriteFromDisk(disk, 'ALIENS/SPR');
            expected = loadGoldenJSON('sprite-ALIENS-SPR.json');
        });

        test('has 2 quads', () => {
            expect(sprite.sprite.length).toBe(2);
            expect(sprite.sprite[0].numSprites).toBe(2);
        });

        test('both quads are multicolor', () => {
            expect(sprite.sprite[0].isMultiColor).toBe(true);
            expect(sprite.sprite[1].isMultiColor).toBe(true);
        });

        test('full sprite matches golden', () => {
            const actual = serializeSprite(sprite);
            expect(actual).toEqual(expected);
        });
    });
});

describe('gmSprite - serialization round-trip', () => {
    let disk;

    beforeAll(() => {
        const data = new Uint8Array(readFileSync(join(DISKS_DIR, 'gmc64-test.d64')));
        disk = new D64(data);
    });

    test('PLAYER/SPR round-trips correctly (single-quad multicolor)', () => {
        const original = loadSpriteFromDisk(disk, 'PLAYER/SPR');
        const reloaded = new gmSprite(original.serialize());
        expect(spritesMatch(original, reloaded)).toBe(true);
    });

    test('ALIENS/SPR round-trips correctly (2-quad multicolor)', () => {
        const original = loadSpriteFromDisk(disk, 'ALIENS/SPR');
        const reloaded = new gmSprite(original.serialize());
        expect(spritesMatch(original, reloaded)).toBe(true);
    });

    test('serialized data produces same size', () => {
        for (const name of ['PLAYER/SPR', 'ALIENS/SPR']) {
            const fileData = disk.readFile(name);
            const sprite = new gmSprite(fileData);
            const serialized = sprite.serialize();
            expect(serialized.length).toBe(fileData.length);
        }
    });

    test('serialized data can be parsed back identically', () => {
        // The serialized bytes may differ in unused/padding fields, but the
        // logical sprite data should be identical when parsed back
        for (const name of ['PLAYER/SPR', 'ALIENS/SPR']) {
            const fileData = disk.readFile(name);
            const original = new gmSprite(fileData);
            const reparsed = new gmSprite(original.serialize());
            expect(serializeSprite(original)).toEqual(serializeSprite(reparsed));
        }
    });
});
